"use client";

import { DatasetCard } from "@/lib/api";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Copy, FileText, Check } from "lucide-react";
import { useState } from "react";

interface DatasetCardViewProps {
    card: DatasetCard;
}

export function DatasetCardView({ card }: DatasetCardViewProps) {
    const [copied, setCopied] = useState(false);

    const getMarkdown = () => {
        return `# ${card.title}

${card.description}

## Intended Use
${card.intended_use}

## Labels
${card.labels.map(l => `- ${l}`).join("\n")}

## Collection Process
${card.collection_process}

## Risks & Biases
${card.risks}

## Limitations
${card.limitations}

## Ethical Considerations
${card.ethical_considerations}

---
*Generated by Ciousten AI*
`;
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(getMarkdown());
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <Card className="mt-6 border-blue-200 dark:border-blue-800 bg-blue-50/50 dark:bg-blue-900/10">
            <CardHeader className="flex flex-row items-center justify-between">
                <CardTitle className="flex items-center gap-2">
                    <FileText className="h-5 w-5 text-blue-600" />
                    Dataset Card (Preview)
                </CardTitle>
                <Button variant="outline" size="sm" onClick={handleCopy}>
                    {copied ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}
                    {copied ? "Copied Markdown" : "Copy Markdown"}
                </Button>
            </CardHeader>
            <CardContent className="prose dark:prose-invert max-w-none text-sm">
                <h3 className="text-xl font-bold mb-2">{card.title}</h3>
                <p className="mb-4">{card.description}</p>

                <div className="grid md:grid-cols-2 gap-6">
                    <div>
                        <h4 className="font-semibold mb-1">Intended Use</h4>
                        <p className="text-muted-foreground mb-4">{card.intended_use}</p>

                        <h4 className="font-semibold mb-1">Labels</h4>
                        <ul className="list-disc pl-5 mb-4">
                            {card.labels.map((l, i) => <li key={i}>{l}</li>)}
                        </ul>
                    </div>
                    <div>
                        <h4 className="font-semibold mb-1">Risks & Limitations</h4>
                        <p className="text-muted-foreground mb-2">{card.risks}</p>
                        <p className="text-muted-foreground mb-4">{card.limitations}</p>

                        <h4 className="font-semibold mb-1">Ethical Considerations</h4>
                        <p className="text-muted-foreground">{card.ethical_considerations}</p>
                    </div>
                </div>
            </CardContent>
        </Card>
    );
}
